defmodule :"Elixir.SuperheroDispatch.Repo.Migrations.Soft-delete-assignments" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:assignments) do
      add :deleted_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:assignments) do
      remove :deleted_at
    end
  end
end
