defmodule SuperheroDispatch.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:superheroes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :hero_alias, :text, null: false
      add :powers, {:array, :text}, default: []
      add :status, :text, null: false, default: "available"
      add :current_location, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:incidents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :incident_number, :text, null: false
      add :incident_type, :text, null: false
      add :description, :text, null: false
      add :location, :text, null: false
      add :priority, :text, null: false, default: "medium"
      add :status, :text, null: false, default: "reported"

      add :reported_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :dispatched_at, :utc_datetime_usec
      add :resolved_at, :utc_datetime_usec
      add :closed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "assigned"
      add :notes, :text

      add :assigned_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :arrived_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :superhero_id,
          references(:superheroes,
            column: :id,
            name: "assignments_superhero_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :incident_id,
          references(:incidents,
            column: :id,
            name: "assignments_incident_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:assignments, "assignments_superhero_id_fkey")

    drop constraint(:assignments, "assignments_incident_id_fkey")

    drop table(:assignments)

    drop table(:incidents)

    drop table(:superheroes)
  end
end
