defmodule SuperheroDispatch.Repo.Migrations.RemoveHeroStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:superheroes) do
      modify :powers, {:array, :text}, null: false
    end

    alter table(:assignments) do
      remove :superhero_status
    end
  end

  def down do
    alter table(:assignments) do
      add :superhero_status, :text, null: false, default: "dispatched"
    end

    alter table(:superheroes) do
      modify :powers, {:array, :text}, null: true
    end
  end
end
