defmodule SuperheroDispatch.Repo.Migrations.AddAssignmentNameAndAlias do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:assignments) do
      add :name, :text, null: false
      add :alias, :text
    end
  end

  def down do
    alter table(:assignments) do
      remove :alias
      remove :name
    end
  end
end
