defmodule SuperheroDispatch.Repo.Migrations.UpdateSuperheroStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:assignments) do
      modify :superhero_status, :text, null: false, default: "dispatched"
      modify :superhero_alias, :text, null: false
    end
  end

  def down do
    alter table(:assignments) do
      modify :superhero_alias, :text, null: true
      modify :superhero_status, :text, null: true, default: nil
    end
  end
end
