defmodule SuperheroDispatch.Repo.Migrations.AddAshArchivalToAssignments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:assignments) do
      remove :deleted_at
      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:assignments) do
      remove :archived_at
      add :deleted_at, :utc_datetime_usec
    end
  end
end
