defmodule SuperheroDispatch.Repo.Migrations.UpdateSuperheroFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:assignments), :name, to: :superhero_name
    rename table(:assignments), :alias, to: :superhero_alias

    alter table(:assignments) do
      add :superhero_status, :text
    end
  end

  def down do
    alter table(:assignments) do
      remove :superhero_status
    end

    rename table(:assignments), :superhero_alias, to: :alias
    rename table(:assignments), :superhero_name, to: :name
  end
end
