defmodule SuperheroDispatch.Repo.Migrations.AddHeroCountToIncidents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:incidents) do
      add :hero_count, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:incidents) do
      remove :hero_count
    end
  end
end
